### ISSUE TITLE
"v2/json/url/stationid" returns wrong url

### ISSUE THREAD

**Issue by haecker-felix** [segler-alex/radiobrowser-api#10]
For some stations the server return wrong urls. 

**For example:**
Radio YleX

it returns:
`http://yleuni-f.akamaihd.net/i/yleliveradiohd_7@113884/segment147547381_128_a-b.ts?sd=10&rebase=on`

which cannot be found. It should be marked as broken or it should return the correct url. 

This happen on all yle (finish) stations.

**Comment by fturco** [comment]
I have the same problem with the m2o radio.

In Gradio:

    ** Message: audio-player.vala:155: Connecting to: http://radiom2o-lh.akamaihd.net/i/RadioM2o_Live_1@42518/segment148596899_96_a-b.ts?sd=10&rebase=on
    ** Message: station-registry.vala:58: [1] is now playing
    ** Message: audio-player.vala:72: Not Found

The right URL is http://radiom2o-lh.akamaihd.net/i/RadioM2o_Live_1@42518/master.m3u8 instead.

**Comment by haecker-felix** [comment]
Fixed.
