### ISSUE TITLE
Handle 302 http status while checking radio station

### ISSUE THREAD

**Issue by koldbyte** [segler-alex/radiobrowser-api#16]
I found some of the radio stations which first give 302 status code and redirect to the actual URL of the stream. 
for example: http://vtuner.com/setupapp/guide/asp/func/dynampls.asp?link=1&id=49509

I have gone through the code and found out that the following line should be modified.
utils.php:101
`if ($statusCode === 400 || $statusCode === 404 || $statusCode === 500 || $statusCode === false) {`

to 

`if ($statusCode === 302 || $statusCode === 400 || $statusCode === 404 || $statusCode === 500 || $statusCode === false) {`

so that cURL kicks in properly in this case. I will prepare a pull request soon after testing it.

Another simple method would be to use cURL always instead of get_headers first.

**Comment by segler-alex** [comment]
thanks, it should be fixed
