### ISSUE TITLE
v2/json/url/streamid  return now list?

### ISSUE THREAD

**Issue by bobo71dream** [segler-alex/radiobrowser-api#18]
hello alex,

`http://www.radio-browser.info/webservice/v2/json/url/74929
`
return now:
`[{"ok":"true","message":"retrieved station url successfully","id":"74929","name":"Antenne Niedersachsen Charts","url":"http:\/\/antenne-nds.hoerradar.de\/mp3-192_antenne-nds-charts?sABC=588260os%230%23r115nr705s0r897o2p4pq98r76o36594%23yvahk&amsparams=playerid:linux;skey:1484939455"}]`

Bug or feature? Regards...

**Comment by segler-alex** [comment]
sorry, i will fix this at once

**Comment by segler-alex** [comment]
should be ok again
