### ISSUE TITLE
Station edit: https:// -> http:/

### ISSUE THREAD

**Issue by haecker-felix** [segler-alex/radiobrowser-api#4]
When I edit a station (url) with following address:

`http://www.radio-browser.info/webservice/json/edit/82299&url=http://antennefranken.de:8001/stream` (Double shlash at http)

the API recognizes this:

`http:/antennefranken.de:8001/stream` (only one slash at http)

The edited station will automatically detected as BROKEN.

(I'm testing this with a development version of gradio (3.0))

**Comment by segler-alex** [comment]
thank you for the bug report. i will have a look at it.
but please don't use plain get requests for this. Use POST requests and send the data encoded with wwwformdata or json like in the docs. especially if you want to support different language encodings!!! if someone from russia uses your app to add/edit a station, this has to be POST

**Comment by haecker-felix** [comment]
@segler-alex yes of course. This feature is mid in development. This was just a test and i noticed this litle bug.

**Comment by segler-alex** [comment]
you have to encode your request like this: (urlencode)
http://www.radio-browser.info/webservice/json/edit/82299?http%3A%2F%2Fantennefranken.de%3A8001%2Fstream

and you have to use "?" to start a query string in http
"&" is only if you have more than one

**Comment by haecker-felix** [comment]
Thanks for the information
