### ISSUE TITLE
Country standard ISO 3166-1 codes

### ISSUE THREAD

**Issue by nesnomis** [segler-alex/radiobrowser-api#5]
I would be nice to have the standard ISO code for country in the api. For example name=Austria, value=AT. 

By using ISO code in value it would make it easier for an application to manage different country names in different languages etc. 

And it could help users to use standard country names (by using a default language name when adding station in the frontend!?).

http://data.okfn.org/data/core/country-list
https://github.com/datasets/country-list
http://www.iso.org/iso/home/standards/country_codes.htm

**Comment by segler-alex** [comment]
i added this to the database

**Comment by segler-alex** [comment]
there is a new countrycache tag for each station, in the frontend the user can only add countries from the api https://restcountries.eu/
