### ISSUE TITLE
Countries mapping

### ISSUE THREAD

**Issue by kuba14** [segler-alex/radiobrowser-api#62]
Different country names (with different streams) are used for one country.
Example:
United States of America
- America
- United States
- United States of America
- US
- USA

I propose creation of mapping array, that would unite streams of these items into one so API would provide radios of only one such country.

The same problem is in web browser in **Search By Countries**.

**Comment by segler-alex** [comment]
countries are fetched from https://restcountries.eu/ and the input field is restricted to only known countries from this service
