### ISSUE TITLE
LanguageCache does NOT work properly

### ISSUE THREAD

**Issue by Zenith-Nadir** [segler-alex/radiobrowser-api#64]
LanguageCache does NOT work properly, not sure of Tags cache, but when selecting some languages (aboriginal, kriolu, etc), which in main stations-languages table are separated by comma-space (", "), do not list any sub-selections / stations), under languages page.
Changing in local stations-languages table comma-space to comma only, seems to correct this.
There are also over 2000 stations with Not-Defined language (NULL), which upon updating local stations-languages table, do NOT synchronize/update  cache table.
There are many more issues with the cache.
Removing duplicates from stations table, does not update cache table.
Main goal is to run local db suitable for ycast project: [https://github.com/milaq/YCast](url).
I managed to clean messy countries selections (which do not rely on cache) with local scripts running upon daily radio-browser db updates, and now I would like to get languages selections cleaned up, so it would resemble a bit more tidy database suitable and working with ycast.
Yet, I am having issues with these cache tables and clean-up.
Maybe there is someone who would explain to understand what correlations are between stations and cache tables and how they are supposed to feed the data to each other.
Unfortunately, I was not able to find it out from radio-browser scripts.
Any constructive suggestions will be very welcome.
Z-N

**Comment by segler-alex** [comment]
this uses other projects for cache handling and checking. stream-check-rust and probably radiobrowser-cleanup-tasks also on my profile. please use radiobrowser-api-rust for future development. it is all in one, but in beta.

**Comment by Zenith-Nadir** [comment]
Hello Alex,
Thanks a lot for such a quick response.
I will see if I can manage with radiobrowser-api-rust, although it seems to install in slightly different directories, I already placed radiobrowser database and radiobrowser gui.
So, far they worked very well on nginx (I am not using apache).
I just need content of the db, but I have noticed similar behavior on your site when selecting some languages, mentioned before, there are empty pages, despite, that in db there are entries.
Well, I will see if I can get somehow languages from stations table to show up in gui, without being redirected to cache table.
Thank you anyway for such a great project.
I wish I knew more how to restrict countries, languages to limited pull down selections entries, to stop  vandal users messing the db and radiobrowser site up.
Sincerely,
Z-N

**Comment by segler-alex** [comment]
i really like your project!! i myself have a device rx-v473 from yamaha
do you need to run radio-browser locally for a test setup or are you planing on completely integrating it? i was also thinking of making a library of the api so you can bundle it. but it is not actively worked on.

**Comment by segler-alex** [comment]
i was just thinking, the api these devices need could also be provided directly from radiobrowser-api-rust. i will look into that

**Comment by segler-alex** [comment]
i will also look into why some languages are not correctly mapped to stations

**Comment by Zenith-Nadir** [comment]
Hello Alex, 
I am so glad you got interested in ycast. Together with radiobrowser, they will conquer the world!
Just to clarify, ycast IT IS NOT MY PROJECT.
It is Micha who started it up: [https://github.com/milaq/YCast](url)
I just got interested in both radio-browser and ycast, when vTuner asked for "RANSOM".
I have approached Micha-ycast if it would be possible to incorporate radio-browser db into ycast.
He did a great job, still in dev branch, but for me working like a charm.
I am not a programmer, that is why I have so much problems to get things together. BUT I DID IT.
In ycast, I got things almost as I would like them to be and should be, and as I would recommend them to my friends.
With radio-browser db, I managed to get around caches issues, we discussed before, by modifying db.php and index.php, and replacing Language/TagsCache calls to Language and Tags calls
My Yamaha RX-V773 (same family as yours) is working almost as vTuner now.
Now, I am trying to clean up languages and tags to make them very transparent, not polluted by ... (you guess by whom).
I need to find feeds from languages and tags fields to caches fields-I will make it.
If possible, how difficult would it be to make adding stations limited by UN (wiki) recognized countries and languages pull down selections, and for analphabets, illiterate users with countries flags and native languages similarly as in available free databases:
[https://www.geonames.org/](url) as an example [https://www.geonames.org/AD/other-names-for-andorra.html](url)
[https://www.ip2location.com/free/country-flags](url)
as in: [https://radiobrowser.com/sort/by/countries](url)
I have tried to figured it out, but it is over my head now. Maybe some time in the future, I would be able to get to this level of programing fluency to get all of this together.
Anyway,
 currently, I am running your project radiobrowser, db and gui, on my local laptop-Ubuntu 18.04LTS on nginx, updating lists daily, cleaning using scripts, and using ycast to enjoy the music.
This is entirely only for my personal use-No business involved whatsoever.
But if anyone would be interested, I am willing to make a fork with modified files from your projects and scripts cleaning db.
I am really grateful for you starting this radiobrowser project.
But if you would like any more info about ycast, please contact Micha ycast developer.
Sincerely,
Z-N

**Comment by segler-alex** [comment]
i will contact micha
currently i am using https://restcountries.eu/ for getting country lists, but i do not force users. they can still add what ever they want. maybe i will change that to better find user-local stations and add only the ISO code to the database
