### ISSUE TITLE
 Some routes are not returning anything.

### ISSUE THREAD

**Issue by andreztz** [segler-alex/radiobrowser-api#69]
Hi, some routes are not returning anything.

When I search for tags composed of words and spaces.
[https://de2.api.radio-browser.info/json/stations/bytag/drum%20and%20bass](https://de2.api.radio-browser.info/json/stations/bytag/drum%20and%20bass)

And when I search for a codec.
https://de2.api.radio-browser.info/json/codecs/mp3

**Comment by segler-alex** [comment]
this issue is in the new api, i fixed it there
